In [ ]:
import pandas as pd
xlsxfile = pd.ExcelFile("riket2023_åk9_np.xlsx")
df = pd.read_excel(xlsxfile)
df.columns = ['Plats', 'Huvudman', 'Totalt(A-F)', 'Flickor(A-F)', 'Pojkar(A-F)', 'Totalt(A-E)', 'Flickor(A-E)', 'Pojkar(A-E)', 'Totalt(poäng)', 'Flickor(poäng)', 'Pojkar(poäng)']
df = df.drop(df.index[:8])
df = df.reset_index(drop=True)
#tar bort skolverket raden för sheet "Svenska som andraspråk" då den inte har någon data och är därför irrelevant
if (df.iloc[3,8] == '..'):
     df = df.drop(df.index[3])

,Grundskolan – Betyg och Prov – Riksnivå,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tabell 1B: Resultat av slutbetyg för elever so...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Läsår\nHuvudman\nBakgrund,Elever som avslutat åk 9 som fått eller skulle...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Genomsnittligt meritvärde beräknat på 16 ämnen,NaN,NaN,Genomsnittligt meritvärde beräknat på 17 ämnen3,NaN,NaN,Andel (%) elever som saknar godkänt betyg i et...,NaN,NaN
6,NaN,Totalt,Flickor,Pojkar,Totalt,Flickor,Pojkar,Totalt,Flickor,Pojkar
7,2018/19,221.7,234.3,209.8,229.8,243.3,217,24.5,21.7,27.2
8,2019/20,222.9,235.7,210.9,231.1,244.9,218.2,23.9,21.4,26.3
9,2020/21,223.9,235.4,212.9,232.1,244.4,220.3,23.9,21.9,25.9
10,2021/22,221.2,231.6,211.4,229.2,240.3,218.8,25.9,24.2,27.5
11,2022/23,220.6,229.7,211.9,228.5,238.2,219.3,26.8,25.5,28
12,därav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Kommun,216.1,225.6,207.2,223.6,233.8,214.1,28.9,27.4,30.3
14,Enskild,237.9,245,230.8,247.2,254.8,239.7,18.7,18.4,19
15,därav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Allmän inriktning,238.5,245.8,231.2,247.9,255.7,240.1,18,17.7,18.3
17,Konfessionell,225.6,230.5,220.5,233.2,238.4,227.8,29.4,29.5,29.4
18,Waldorf,236.3,239,233.9,244.3,247.1,241.7,25.6,25.3,25.8
19,Elever med svensk bakgrund,227.4,236.3,219.1,236,245.4,227.1,21.4,20.5,22.2
20,Elever med utländsk bakgrund,204,214.1,194.5,210.2,221,200.1,40.2,37.8,42.5
21,därav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Födda i Sverige,215.5,224.7,206.6,223,232.8,213.5,32.6,30.8,34.3
23,"Födda utomlands, inv. före 2014",217.4,227.6,208,224.8,235.8,214.7,32,29.8,34
24,"Födda utomlands, inv. 2014 el. senare",182.1,193.1,171.8,186.1,197.7,175.1,54.3,51.1,57.2
25,Totalt exkl. nyinvandrade elever och okänd bak...,223,232.1,214.3,231.1,240.9,221.7,25.2,24,26.4
26,Nyinvandrade elever,144.8,152,138.2,146.2,153.6,139.3,75,72.9,77
27,Elever med okänd bakgrund,133.3,133.9,132.8,135.2,135.8,134.6,77.9,79.8,76.1
28,Föräldrarnas högsta utbildning2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Förgymnasial utbildning,163.8,172.2,155.8,166.8,175.6,158.3,63.5,61.5,65.3